version: '3.8'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://backend:443/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    image: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=343539544
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Certificates.p12
      - ConnectionStrings__ApplicationDbContext=Server=tcp:msaprojectserver.database.windows.net,1433;Initial Catalog=MsaProject;Persist Security Info=False;User ID=zdybaijixiong;Password=ZDYzdy123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=60;
      - JwtSettings__SecretKey=B8Kp392sRQma0q5LgN9Jwngjc4HEa4fgQW9V40L9dP77LzbzLMZyoR7zgw4jK2AG
      - JwtSettings__Issuer=MsaProjectIssuer
      - JwtSettings__Audience=MsaProjectAudience
      - JwtSettings__ExpirationMinutes=1440
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: msa_project-network
